// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER FILE — replace this by running `flutterfire configure` in
/// the project root after you have created a Firebase project. That command
/// overwrites this file with your project's real API keys and app IDs for
/// each platform (web, android). See README.md, step "Connect Firebase".
///
/// Do NOT ship the placeholder values below — the app will fail to connect
/// to Firebase until this file is regenerated.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate them.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvgFDkCLP-1326B1uTLjTi3jQ6XkYUN8',
    appId: '1:88120463965:web:04ffe061619c49210a73b4',
    messagingSenderId: '88120463965',
    projectId: 'blood-bank-app-50253',
    authDomain: 'blood-bank-app-50253.firebaseapp.com',
    storageBucket: 'blood-bank-app-50253.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0PrRmfh_F9H5dZyQ-hfLsDWM7ui42d0w',
    appId: '1:88120463965:android:c650a265174642140a73b4',
    messagingSenderId: '88120463965',
    projectId: 'blood-bank-app-50253',
    storageBucket: 'blood-bank-app-50253.firebasestorage.app',
  );
}
